package com.cibr.vectorservice.entity;

public class CibrConfigGroupsetting {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_config_groupsetting.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_config_groupsetting.groupid
     *
     * @mbggenerated
     */
    private String groupid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_config_groupsetting.email
     *
     * @mbggenerated
     */
    private Boolean email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_config_groupsetting.groupName
     *
     * @mbggenerated
     */
    private String groupname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_config_groupsetting.id
     *
     * @return the value of cibr_config_groupsetting.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_config_groupsetting.id
     *
     * @param id the value for cibr_config_groupsetting.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_config_groupsetting.groupid
     *
     * @return the value of cibr_config_groupsetting.groupid
     *
     * @mbggenerated
     */
    public String getGroupid() {
        return groupid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_config_groupsetting.groupid
     *
     * @param groupid the value for cibr_config_groupsetting.groupid
     *
     * @mbggenerated
     */
    public void setGroupid(String groupid) {
        this.groupid = groupid == null ? null : groupid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_config_groupsetting.email
     *
     * @return the value of cibr_config_groupsetting.email
     *
     * @mbggenerated
     */
    public Boolean getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_config_groupsetting.email
     *
     * @param email the value for cibr_config_groupsetting.email
     *
     * @mbggenerated
     */
    public void setEmail(Boolean email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_config_groupsetting.groupName
     *
     * @return the value of cibr_config_groupsetting.groupName
     *
     * @mbggenerated
     */
    public String getGroupname() {
        return groupname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_config_groupsetting.groupName
     *
     * @param groupname the value for cibr_config_groupsetting.groupName
     *
     * @mbggenerated
     */
    public void setGroupname(String groupname) {
        this.groupname = groupname == null ? null : groupname.trim();
    }
}