package com.cibr.vectorservice.entity;

import java.util.Date;

public class CibrTaskRaav {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_task_raav.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_task_raav.constructName
     *
     * @mbggenerated
     */
    private String constructname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_task_raav.materialprovided
     *
     * @mbggenerated
     */
    private String materialprovided;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_task_raav.generisk
     *
     * @mbggenerated
     */
    private String generisk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_task_raav.serotype
     *
     * @mbggenerated
     */
    private String serotype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_task_raav.sharing
     *
     * @mbggenerated
     */
    private Boolean sharing;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_task_raav.requestNum
     *
     * @mbggenerated
     */
    private Integer requestnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_task_raav.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_task_raav.vol
     *
     * @mbggenerated
     */
    private String vol;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_task_raav.titer
     *
     * @mbggenerated
     */
    private String titer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_task_raav.creater
     *
     * @mbggenerated
     */
    private String creater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_task_raav.taskid
     *
     * @mbggenerated
     */
    private String taskid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_task_raav.createtime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_task_raav.curstatu
     *
     * @mbggenerated
     */
    private String curstatu;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_task_raav.id
     *
     * @return the value of cibr_task_raav.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_task_raav.id
     *
     * @param id the value for cibr_task_raav.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_task_raav.constructName
     *
     * @return the value of cibr_task_raav.constructName
     *
     * @mbggenerated
     */
    public String getConstructname() {
        return constructname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_task_raav.constructName
     *
     * @param constructname the value for cibr_task_raav.constructName
     *
     * @mbggenerated
     */
    public void setConstructname(String constructname) {
        this.constructname = constructname == null ? null : constructname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_task_raav.materialprovided
     *
     * @return the value of cibr_task_raav.materialprovided
     *
     * @mbggenerated
     */
    public String getMaterialprovided() {
        return materialprovided;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_task_raav.materialprovided
     *
     * @param materialprovided the value for cibr_task_raav.materialprovided
     *
     * @mbggenerated
     */
    public void setMaterialprovided(String materialprovided) {
        this.materialprovided = materialprovided == null ? null : materialprovided.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_task_raav.generisk
     *
     * @return the value of cibr_task_raav.generisk
     *
     * @mbggenerated
     */
    public String getGenerisk() {
        return generisk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_task_raav.generisk
     *
     * @param generisk the value for cibr_task_raav.generisk
     *
     * @mbggenerated
     */
    public void setGenerisk(String generisk) {
        this.generisk = generisk == null ? null : generisk.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_task_raav.serotype
     *
     * @return the value of cibr_task_raav.serotype
     *
     * @mbggenerated
     */
    public String getSerotype() {
        return serotype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_task_raav.serotype
     *
     * @param serotype the value for cibr_task_raav.serotype
     *
     * @mbggenerated
     */
    public void setSerotype(String serotype) {
        this.serotype = serotype == null ? null : serotype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_task_raav.sharing
     *
     * @return the value of cibr_task_raav.sharing
     *
     * @mbggenerated
     */
    public Boolean getSharing() {
        return sharing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_task_raav.sharing
     *
     * @param sharing the value for cibr_task_raav.sharing
     *
     * @mbggenerated
     */
    public void setSharing(Boolean sharing) {
        this.sharing = sharing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_task_raav.requestNum
     *
     * @return the value of cibr_task_raav.requestNum
     *
     * @mbggenerated
     */
    public Integer getRequestnum() {
        return requestnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_task_raav.requestNum
     *
     * @param requestnum the value for cibr_task_raav.requestNum
     *
     * @mbggenerated
     */
    public void setRequestnum(Integer requestnum) {
        this.requestnum = requestnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_task_raav.remark
     *
     * @return the value of cibr_task_raav.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_task_raav.remark
     *
     * @param remark the value for cibr_task_raav.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_task_raav.vol
     *
     * @return the value of cibr_task_raav.vol
     *
     * @mbggenerated
     */
    public String getVol() {
        return vol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_task_raav.vol
     *
     * @param vol the value for cibr_task_raav.vol
     *
     * @mbggenerated
     */
    public void setVol(String vol) {
        this.vol = vol == null ? null : vol.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_task_raav.titer
     *
     * @return the value of cibr_task_raav.titer
     *
     * @mbggenerated
     */
    public String getTiter() {
        return titer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_task_raav.titer
     *
     * @param titer the value for cibr_task_raav.titer
     *
     * @mbggenerated
     */
    public void setTiter(String titer) {
        this.titer = titer == null ? null : titer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_task_raav.creater
     *
     * @return the value of cibr_task_raav.creater
     *
     * @mbggenerated
     */
    public String getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_task_raav.creater
     *
     * @param creater the value for cibr_task_raav.creater
     *
     * @mbggenerated
     */
    public void setCreater(String creater) {
        this.creater = creater == null ? null : creater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_task_raav.taskid
     *
     * @return the value of cibr_task_raav.taskid
     *
     * @mbggenerated
     */
    public String getTaskid() {
        return taskid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_task_raav.taskid
     *
     * @param taskid the value for cibr_task_raav.taskid
     *
     * @mbggenerated
     */
    public void setTaskid(String taskid) {
        this.taskid = taskid == null ? null : taskid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_task_raav.createtime
     *
     * @return the value of cibr_task_raav.createtime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_task_raav.createtime
     *
     * @param createtime the value for cibr_task_raav.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_task_raav.curstatu
     *
     * @return the value of cibr_task_raav.curstatu
     *
     * @mbggenerated
     */
    public String getCurstatu() {
        return curstatu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_task_raav.curstatu
     *
     * @param curstatu the value for cibr_task_raav.curstatu
     *
     * @mbggenerated
     */
    public void setCurstatu(String curstatu) {
        this.curstatu = curstatu == null ? null : curstatu.trim();
    }
}