package com.cibr.vectorservice.entity;

import java.util.Date;

public class CibrConfigSelect {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_config_select.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_config_select.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_config_select.enname
     *
     * @mbggenerated
     */
    private String enname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_config_select.createtime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_config_select.selectType
     *
     * @mbggenerated
     */
    private String selecttype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_config_select.parentId
     *
     * @mbggenerated
     */
    private String parentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_config_select.curstatu
     *
     * @mbggenerated
     */
    private String curstatu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_config_select.pagetype
     *
     * @mbggenerated
     */
    private String pagetype;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_config_select.id
     *
     * @return the value of cibr_config_select.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_config_select.id
     *
     * @param id the value for cibr_config_select.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_config_select.name
     *
     * @return the value of cibr_config_select.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_config_select.name
     *
     * @param name the value for cibr_config_select.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_config_select.enname
     *
     * @return the value of cibr_config_select.enname
     *
     * @mbggenerated
     */
    public String getEnname() {
        return enname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_config_select.enname
     *
     * @param enname the value for cibr_config_select.enname
     *
     * @mbggenerated
     */
    public void setEnname(String enname) {
        this.enname = enname == null ? null : enname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_config_select.createtime
     *
     * @return the value of cibr_config_select.createtime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_config_select.createtime
     *
     * @param createtime the value for cibr_config_select.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_config_select.selectType
     *
     * @return the value of cibr_config_select.selectType
     *
     * @mbggenerated
     */
    public String getSelecttype() {
        return selecttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_config_select.selectType
     *
     * @param selecttype the value for cibr_config_select.selectType
     *
     * @mbggenerated
     */
    public void setSelecttype(String selecttype) {
        this.selecttype = selecttype == null ? null : selecttype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_config_select.parentId
     *
     * @return the value of cibr_config_select.parentId
     *
     * @mbggenerated
     */
    public String getParentid() {
        return parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_config_select.parentId
     *
     * @param parentid the value for cibr_config_select.parentId
     *
     * @mbggenerated
     */
    public void setParentid(String parentid) {
        this.parentid = parentid == null ? null : parentid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_config_select.curstatu
     *
     * @return the value of cibr_config_select.curstatu
     *
     * @mbggenerated
     */
    public String getCurstatu() {
        return curstatu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_config_select.curstatu
     *
     * @param curstatu the value for cibr_config_select.curstatu
     *
     * @mbggenerated
     */
    public void setCurstatu(String curstatu) {
        this.curstatu = curstatu == null ? null : curstatu.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_config_select.pagetype
     *
     * @return the value of cibr_config_select.pagetype
     *
     * @mbggenerated
     */
    public String getPagetype() {
        return pagetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_config_select.pagetype
     *
     * @param pagetype the value for cibr_config_select.pagetype
     *
     * @mbggenerated
     */
    public void setPagetype(String pagetype) {
        this.pagetype = pagetype == null ? null : pagetype.trim();
    }
}