package com.cibr.vectorservice.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CibrTaskRaavExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cibr_task_raav
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cibr_task_raav
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cibr_task_raav
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_raav
     *
     * @mbggenerated
     */
    public CibrTaskRaavExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_raav
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_raav
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_raav
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_raav
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_raav
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_raav
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_raav
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_raav
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_raav
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_raav
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cibr_task_raav
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andConstructnameIsNull() {
            addCriterion("constructName is null");
            return (Criteria) this;
        }

        public Criteria andConstructnameIsNotNull() {
            addCriterion("constructName is not null");
            return (Criteria) this;
        }

        public Criteria andConstructnameEqualTo(String value) {
            addCriterion("constructName =", value, "constructname");
            return (Criteria) this;
        }

        public Criteria andConstructnameNotEqualTo(String value) {
            addCriterion("constructName <>", value, "constructname");
            return (Criteria) this;
        }

        public Criteria andConstructnameGreaterThan(String value) {
            addCriterion("constructName >", value, "constructname");
            return (Criteria) this;
        }

        public Criteria andConstructnameGreaterThanOrEqualTo(String value) {
            addCriterion("constructName >=", value, "constructname");
            return (Criteria) this;
        }

        public Criteria andConstructnameLessThan(String value) {
            addCriterion("constructName <", value, "constructname");
            return (Criteria) this;
        }

        public Criteria andConstructnameLessThanOrEqualTo(String value) {
            addCriterion("constructName <=", value, "constructname");
            return (Criteria) this;
        }

        public Criteria andConstructnameLike(String value) {
            addCriterion("constructName like", value, "constructname");
            return (Criteria) this;
        }

        public Criteria andConstructnameNotLike(String value) {
            addCriterion("constructName not like", value, "constructname");
            return (Criteria) this;
        }

        public Criteria andConstructnameIn(List<String> values) {
            addCriterion("constructName in", values, "constructname");
            return (Criteria) this;
        }

        public Criteria andConstructnameNotIn(List<String> values) {
            addCriterion("constructName not in", values, "constructname");
            return (Criteria) this;
        }

        public Criteria andConstructnameBetween(String value1, String value2) {
            addCriterion("constructName between", value1, value2, "constructname");
            return (Criteria) this;
        }

        public Criteria andConstructnameNotBetween(String value1, String value2) {
            addCriterion("constructName not between", value1, value2, "constructname");
            return (Criteria) this;
        }

        public Criteria andMaterialprovidedIsNull() {
            addCriterion("materialprovided is null");
            return (Criteria) this;
        }

        public Criteria andMaterialprovidedIsNotNull() {
            addCriterion("materialprovided is not null");
            return (Criteria) this;
        }

        public Criteria andMaterialprovidedEqualTo(String value) {
            addCriterion("materialprovided =", value, "materialprovided");
            return (Criteria) this;
        }

        public Criteria andMaterialprovidedNotEqualTo(String value) {
            addCriterion("materialprovided <>", value, "materialprovided");
            return (Criteria) this;
        }

        public Criteria andMaterialprovidedGreaterThan(String value) {
            addCriterion("materialprovided >", value, "materialprovided");
            return (Criteria) this;
        }

        public Criteria andMaterialprovidedGreaterThanOrEqualTo(String value) {
            addCriterion("materialprovided >=", value, "materialprovided");
            return (Criteria) this;
        }

        public Criteria andMaterialprovidedLessThan(String value) {
            addCriterion("materialprovided <", value, "materialprovided");
            return (Criteria) this;
        }

        public Criteria andMaterialprovidedLessThanOrEqualTo(String value) {
            addCriterion("materialprovided <=", value, "materialprovided");
            return (Criteria) this;
        }

        public Criteria andMaterialprovidedLike(String value) {
            addCriterion("materialprovided like", value, "materialprovided");
            return (Criteria) this;
        }

        public Criteria andMaterialprovidedNotLike(String value) {
            addCriterion("materialprovided not like", value, "materialprovided");
            return (Criteria) this;
        }

        public Criteria andMaterialprovidedIn(List<String> values) {
            addCriterion("materialprovided in", values, "materialprovided");
            return (Criteria) this;
        }

        public Criteria andMaterialprovidedNotIn(List<String> values) {
            addCriterion("materialprovided not in", values, "materialprovided");
            return (Criteria) this;
        }

        public Criteria andMaterialprovidedBetween(String value1, String value2) {
            addCriterion("materialprovided between", value1, value2, "materialprovided");
            return (Criteria) this;
        }

        public Criteria andMaterialprovidedNotBetween(String value1, String value2) {
            addCriterion("materialprovided not between", value1, value2, "materialprovided");
            return (Criteria) this;
        }

        public Criteria andGeneriskIsNull() {
            addCriterion("generisk is null");
            return (Criteria) this;
        }

        public Criteria andGeneriskIsNotNull() {
            addCriterion("generisk is not null");
            return (Criteria) this;
        }

        public Criteria andGeneriskEqualTo(String value) {
            addCriterion("generisk =", value, "generisk");
            return (Criteria) this;
        }

        public Criteria andGeneriskNotEqualTo(String value) {
            addCriterion("generisk <>", value, "generisk");
            return (Criteria) this;
        }

        public Criteria andGeneriskGreaterThan(String value) {
            addCriterion("generisk >", value, "generisk");
            return (Criteria) this;
        }

        public Criteria andGeneriskGreaterThanOrEqualTo(String value) {
            addCriterion("generisk >=", value, "generisk");
            return (Criteria) this;
        }

        public Criteria andGeneriskLessThan(String value) {
            addCriterion("generisk <", value, "generisk");
            return (Criteria) this;
        }

        public Criteria andGeneriskLessThanOrEqualTo(String value) {
            addCriterion("generisk <=", value, "generisk");
            return (Criteria) this;
        }

        public Criteria andGeneriskLike(String value) {
            addCriterion("generisk like", value, "generisk");
            return (Criteria) this;
        }

        public Criteria andGeneriskNotLike(String value) {
            addCriterion("generisk not like", value, "generisk");
            return (Criteria) this;
        }

        public Criteria andGeneriskIn(List<String> values) {
            addCriterion("generisk in", values, "generisk");
            return (Criteria) this;
        }

        public Criteria andGeneriskNotIn(List<String> values) {
            addCriterion("generisk not in", values, "generisk");
            return (Criteria) this;
        }

        public Criteria andGeneriskBetween(String value1, String value2) {
            addCriterion("generisk between", value1, value2, "generisk");
            return (Criteria) this;
        }

        public Criteria andGeneriskNotBetween(String value1, String value2) {
            addCriterion("generisk not between", value1, value2, "generisk");
            return (Criteria) this;
        }

        public Criteria andSerotypeIsNull() {
            addCriterion("serotype is null");
            return (Criteria) this;
        }

        public Criteria andSerotypeIsNotNull() {
            addCriterion("serotype is not null");
            return (Criteria) this;
        }

        public Criteria andSerotypeEqualTo(String value) {
            addCriterion("serotype =", value, "serotype");
            return (Criteria) this;
        }

        public Criteria andSerotypeNotEqualTo(String value) {
            addCriterion("serotype <>", value, "serotype");
            return (Criteria) this;
        }

        public Criteria andSerotypeGreaterThan(String value) {
            addCriterion("serotype >", value, "serotype");
            return (Criteria) this;
        }

        public Criteria andSerotypeGreaterThanOrEqualTo(String value) {
            addCriterion("serotype >=", value, "serotype");
            return (Criteria) this;
        }

        public Criteria andSerotypeLessThan(String value) {
            addCriterion("serotype <", value, "serotype");
            return (Criteria) this;
        }

        public Criteria andSerotypeLessThanOrEqualTo(String value) {
            addCriterion("serotype <=", value, "serotype");
            return (Criteria) this;
        }

        public Criteria andSerotypeLike(String value) {
            addCriterion("serotype like", value, "serotype");
            return (Criteria) this;
        }

        public Criteria andSerotypeNotLike(String value) {
            addCriterion("serotype not like", value, "serotype");
            return (Criteria) this;
        }

        public Criteria andSerotypeIn(List<String> values) {
            addCriterion("serotype in", values, "serotype");
            return (Criteria) this;
        }

        public Criteria andSerotypeNotIn(List<String> values) {
            addCriterion("serotype not in", values, "serotype");
            return (Criteria) this;
        }

        public Criteria andSerotypeBetween(String value1, String value2) {
            addCriterion("serotype between", value1, value2, "serotype");
            return (Criteria) this;
        }

        public Criteria andSerotypeNotBetween(String value1, String value2) {
            addCriterion("serotype not between", value1, value2, "serotype");
            return (Criteria) this;
        }

        public Criteria andSharingIsNull() {
            addCriterion("sharing is null");
            return (Criteria) this;
        }

        public Criteria andSharingIsNotNull() {
            addCriterion("sharing is not null");
            return (Criteria) this;
        }

        public Criteria andSharingEqualTo(Boolean value) {
            addCriterion("sharing =", value, "sharing");
            return (Criteria) this;
        }

        public Criteria andSharingNotEqualTo(Boolean value) {
            addCriterion("sharing <>", value, "sharing");
            return (Criteria) this;
        }

        public Criteria andSharingGreaterThan(Boolean value) {
            addCriterion("sharing >", value, "sharing");
            return (Criteria) this;
        }

        public Criteria andSharingGreaterThanOrEqualTo(Boolean value) {
            addCriterion("sharing >=", value, "sharing");
            return (Criteria) this;
        }

        public Criteria andSharingLessThan(Boolean value) {
            addCriterion("sharing <", value, "sharing");
            return (Criteria) this;
        }

        public Criteria andSharingLessThanOrEqualTo(Boolean value) {
            addCriterion("sharing <=", value, "sharing");
            return (Criteria) this;
        }

        public Criteria andSharingIn(List<Boolean> values) {
            addCriterion("sharing in", values, "sharing");
            return (Criteria) this;
        }

        public Criteria andSharingNotIn(List<Boolean> values) {
            addCriterion("sharing not in", values, "sharing");
            return (Criteria) this;
        }

        public Criteria andSharingBetween(Boolean value1, Boolean value2) {
            addCriterion("sharing between", value1, value2, "sharing");
            return (Criteria) this;
        }

        public Criteria andSharingNotBetween(Boolean value1, Boolean value2) {
            addCriterion("sharing not between", value1, value2, "sharing");
            return (Criteria) this;
        }

        public Criteria andRequestnumIsNull() {
            addCriterion("requestNum is null");
            return (Criteria) this;
        }

        public Criteria andRequestnumIsNotNull() {
            addCriterion("requestNum is not null");
            return (Criteria) this;
        }

        public Criteria andRequestnumEqualTo(Integer value) {
            addCriterion("requestNum =", value, "requestnum");
            return (Criteria) this;
        }

        public Criteria andRequestnumNotEqualTo(Integer value) {
            addCriterion("requestNum <>", value, "requestnum");
            return (Criteria) this;
        }

        public Criteria andRequestnumGreaterThan(Integer value) {
            addCriterion("requestNum >", value, "requestnum");
            return (Criteria) this;
        }

        public Criteria andRequestnumGreaterThanOrEqualTo(Integer value) {
            addCriterion("requestNum >=", value, "requestnum");
            return (Criteria) this;
        }

        public Criteria andRequestnumLessThan(Integer value) {
            addCriterion("requestNum <", value, "requestnum");
            return (Criteria) this;
        }

        public Criteria andRequestnumLessThanOrEqualTo(Integer value) {
            addCriterion("requestNum <=", value, "requestnum");
            return (Criteria) this;
        }

        public Criteria andRequestnumIn(List<Integer> values) {
            addCriterion("requestNum in", values, "requestnum");
            return (Criteria) this;
        }

        public Criteria andRequestnumNotIn(List<Integer> values) {
            addCriterion("requestNum not in", values, "requestnum");
            return (Criteria) this;
        }

        public Criteria andRequestnumBetween(Integer value1, Integer value2) {
            addCriterion("requestNum between", value1, value2, "requestnum");
            return (Criteria) this;
        }

        public Criteria andRequestnumNotBetween(Integer value1, Integer value2) {
            addCriterion("requestNum not between", value1, value2, "requestnum");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("remark is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("remark is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("remark =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("remark <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("remark >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("remark >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("remark <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("remark <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("remark like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("remark not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("remark in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("remark not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("remark between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("remark not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andVolIsNull() {
            addCriterion("vol is null");
            return (Criteria) this;
        }

        public Criteria andVolIsNotNull() {
            addCriterion("vol is not null");
            return (Criteria) this;
        }

        public Criteria andVolEqualTo(String value) {
            addCriterion("vol =", value, "vol");
            return (Criteria) this;
        }

        public Criteria andVolNotEqualTo(String value) {
            addCriterion("vol <>", value, "vol");
            return (Criteria) this;
        }

        public Criteria andVolGreaterThan(String value) {
            addCriterion("vol >", value, "vol");
            return (Criteria) this;
        }

        public Criteria andVolGreaterThanOrEqualTo(String value) {
            addCriterion("vol >=", value, "vol");
            return (Criteria) this;
        }

        public Criteria andVolLessThan(String value) {
            addCriterion("vol <", value, "vol");
            return (Criteria) this;
        }

        public Criteria andVolLessThanOrEqualTo(String value) {
            addCriterion("vol <=", value, "vol");
            return (Criteria) this;
        }

        public Criteria andVolLike(String value) {
            addCriterion("vol like", value, "vol");
            return (Criteria) this;
        }

        public Criteria andVolNotLike(String value) {
            addCriterion("vol not like", value, "vol");
            return (Criteria) this;
        }

        public Criteria andVolIn(List<String> values) {
            addCriterion("vol in", values, "vol");
            return (Criteria) this;
        }

        public Criteria andVolNotIn(List<String> values) {
            addCriterion("vol not in", values, "vol");
            return (Criteria) this;
        }

        public Criteria andVolBetween(String value1, String value2) {
            addCriterion("vol between", value1, value2, "vol");
            return (Criteria) this;
        }

        public Criteria andVolNotBetween(String value1, String value2) {
            addCriterion("vol not between", value1, value2, "vol");
            return (Criteria) this;
        }

        public Criteria andTiterIsNull() {
            addCriterion("titer is null");
            return (Criteria) this;
        }

        public Criteria andTiterIsNotNull() {
            addCriterion("titer is not null");
            return (Criteria) this;
        }

        public Criteria andTiterEqualTo(String value) {
            addCriterion("titer =", value, "titer");
            return (Criteria) this;
        }

        public Criteria andTiterNotEqualTo(String value) {
            addCriterion("titer <>", value, "titer");
            return (Criteria) this;
        }

        public Criteria andTiterGreaterThan(String value) {
            addCriterion("titer >", value, "titer");
            return (Criteria) this;
        }

        public Criteria andTiterGreaterThanOrEqualTo(String value) {
            addCriterion("titer >=", value, "titer");
            return (Criteria) this;
        }

        public Criteria andTiterLessThan(String value) {
            addCriterion("titer <", value, "titer");
            return (Criteria) this;
        }

        public Criteria andTiterLessThanOrEqualTo(String value) {
            addCriterion("titer <=", value, "titer");
            return (Criteria) this;
        }

        public Criteria andTiterLike(String value) {
            addCriterion("titer like", value, "titer");
            return (Criteria) this;
        }

        public Criteria andTiterNotLike(String value) {
            addCriterion("titer not like", value, "titer");
            return (Criteria) this;
        }

        public Criteria andTiterIn(List<String> values) {
            addCriterion("titer in", values, "titer");
            return (Criteria) this;
        }

        public Criteria andTiterNotIn(List<String> values) {
            addCriterion("titer not in", values, "titer");
            return (Criteria) this;
        }

        public Criteria andTiterBetween(String value1, String value2) {
            addCriterion("titer between", value1, value2, "titer");
            return (Criteria) this;
        }

        public Criteria andTiterNotBetween(String value1, String value2) {
            addCriterion("titer not between", value1, value2, "titer");
            return (Criteria) this;
        }

        public Criteria andCreaterIsNull() {
            addCriterion("creater is null");
            return (Criteria) this;
        }

        public Criteria andCreaterIsNotNull() {
            addCriterion("creater is not null");
            return (Criteria) this;
        }

        public Criteria andCreaterEqualTo(String value) {
            addCriterion("creater =", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterNotEqualTo(String value) {
            addCriterion("creater <>", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterGreaterThan(String value) {
            addCriterion("creater >", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterGreaterThanOrEqualTo(String value) {
            addCriterion("creater >=", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterLessThan(String value) {
            addCriterion("creater <", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterLessThanOrEqualTo(String value) {
            addCriterion("creater <=", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterLike(String value) {
            addCriterion("creater like", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterNotLike(String value) {
            addCriterion("creater not like", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterIn(List<String> values) {
            addCriterion("creater in", values, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterNotIn(List<String> values) {
            addCriterion("creater not in", values, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterBetween(String value1, String value2) {
            addCriterion("creater between", value1, value2, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterNotBetween(String value1, String value2) {
            addCriterion("creater not between", value1, value2, "creater");
            return (Criteria) this;
        }

        public Criteria andTaskidIsNull() {
            addCriterion("taskid is null");
            return (Criteria) this;
        }

        public Criteria andTaskidIsNotNull() {
            addCriterion("taskid is not null");
            return (Criteria) this;
        }

        public Criteria andTaskidEqualTo(String value) {
            addCriterion("taskid =", value, "taskid");
            return (Criteria) this;
        }

        public Criteria andTaskidNotEqualTo(String value) {
            addCriterion("taskid <>", value, "taskid");
            return (Criteria) this;
        }

        public Criteria andTaskidGreaterThan(String value) {
            addCriterion("taskid >", value, "taskid");
            return (Criteria) this;
        }

        public Criteria andTaskidGreaterThanOrEqualTo(String value) {
            addCriterion("taskid >=", value, "taskid");
            return (Criteria) this;
        }

        public Criteria andTaskidLessThan(String value) {
            addCriterion("taskid <", value, "taskid");
            return (Criteria) this;
        }

        public Criteria andTaskidLessThanOrEqualTo(String value) {
            addCriterion("taskid <=", value, "taskid");
            return (Criteria) this;
        }

        public Criteria andTaskidLike(String value) {
            addCriterion("taskid like", value, "taskid");
            return (Criteria) this;
        }

        public Criteria andTaskidNotLike(String value) {
            addCriterion("taskid not like", value, "taskid");
            return (Criteria) this;
        }

        public Criteria andTaskidIn(List<String> values) {
            addCriterion("taskid in", values, "taskid");
            return (Criteria) this;
        }

        public Criteria andTaskidNotIn(List<String> values) {
            addCriterion("taskid not in", values, "taskid");
            return (Criteria) this;
        }

        public Criteria andTaskidBetween(String value1, String value2) {
            addCriterion("taskid between", value1, value2, "taskid");
            return (Criteria) this;
        }

        public Criteria andTaskidNotBetween(String value1, String value2) {
            addCriterion("taskid not between", value1, value2, "taskid");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNull() {
            addCriterion("createtime is null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNotNull() {
            addCriterion("createtime is not null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeEqualTo(Date value) {
            addCriterion("createtime =", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotEqualTo(Date value) {
            addCriterion("createtime <>", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThan(Date value) {
            addCriterion("createtime >", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("createtime >=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThan(Date value) {
            addCriterion("createtime <", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThanOrEqualTo(Date value) {
            addCriterion("createtime <=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIn(List<Date> values) {
            addCriterion("createtime in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotIn(List<Date> values) {
            addCriterion("createtime not in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeBetween(Date value1, Date value2) {
            addCriterion("createtime between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotBetween(Date value1, Date value2) {
            addCriterion("createtime not between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andCurstatuIsNull() {
            addCriterion("curstatu is null");
            return (Criteria) this;
        }

        public Criteria andCurstatuIsNotNull() {
            addCriterion("curstatu is not null");
            return (Criteria) this;
        }

        public Criteria andCurstatuEqualTo(String value) {
            addCriterion("curstatu =", value, "curstatu");
            return (Criteria) this;
        }

        public Criteria andCurstatuNotEqualTo(String value) {
            addCriterion("curstatu <>", value, "curstatu");
            return (Criteria) this;
        }

        public Criteria andCurstatuGreaterThan(String value) {
            addCriterion("curstatu >", value, "curstatu");
            return (Criteria) this;
        }

        public Criteria andCurstatuGreaterThanOrEqualTo(String value) {
            addCriterion("curstatu >=", value, "curstatu");
            return (Criteria) this;
        }

        public Criteria andCurstatuLessThan(String value) {
            addCriterion("curstatu <", value, "curstatu");
            return (Criteria) this;
        }

        public Criteria andCurstatuLessThanOrEqualTo(String value) {
            addCriterion("curstatu <=", value, "curstatu");
            return (Criteria) this;
        }

        public Criteria andCurstatuLike(String value) {
            addCriterion("curstatu like", value, "curstatu");
            return (Criteria) this;
        }

        public Criteria andCurstatuNotLike(String value) {
            addCriterion("curstatu not like", value, "curstatu");
            return (Criteria) this;
        }

        public Criteria andCurstatuIn(List<String> values) {
            addCriterion("curstatu in", values, "curstatu");
            return (Criteria) this;
        }

        public Criteria andCurstatuNotIn(List<String> values) {
            addCriterion("curstatu not in", values, "curstatu");
            return (Criteria) this;
        }

        public Criteria andCurstatuBetween(String value1, String value2) {
            addCriterion("curstatu between", value1, value2, "curstatu");
            return (Criteria) this;
        }

        public Criteria andCurstatuNotBetween(String value1, String value2) {
            addCriterion("curstatu not between", value1, value2, "curstatu");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cibr_task_raav
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cibr_task_raav
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}