package com.cibr.vectorservice.entity;

import java.util.Date;
import java.util.List;

public class CibrSysTask {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_sys_task.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_sys_task.taskName
     *
     * @mbggenerated
     */
    private String taskname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_sys_task.taskType
     *
     * @mbggenerated
     */
    private String tasktype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_sys_task.taskstatu
     *
     * @mbggenerated
     */
    private String taskstatu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_sys_task.creater
     *
     * @mbggenerated
     */
    private String creater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_sys_task.createTime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_sys_task.remark
     *
     * @mbggenerated
     */
    private String remark;

    private List<CibrTaskRaav> raavs;

    private CibrTaskFail fail;

    private CibrSysEvaluation evaluation;

    private String groupAdmin;

    private int before;

    public int getBefore() {
        return before;
    }

    public void setBefore(int before) {
        this.before = before;
    }

    public String getGroupAdmin() {
        return groupAdmin;
    }

    public void setGroupAdmin(String groupAdmin) {
        this.groupAdmin = groupAdmin;
    }

    public CibrSysEvaluation getEvaluation() {
        return evaluation;
    }

    public void setEvaluation(CibrSysEvaluation evaluation) {
        this.evaluation = evaluation;
    }

    public CibrTaskFail getFail() {
        return fail;
    }

    public void setFail(CibrTaskFail fail) {
        this.fail = fail;
    }

    public List<CibrTaskRaav> getRaavs() {
        return raavs;
    }

    public void setRaavs(List<CibrTaskRaav> raavs) {
        this.raavs = raavs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_sys_task.id
     *
     * @return the value of cibr_sys_task.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_sys_task.id
     *
     * @param id the value for cibr_sys_task.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_sys_task.taskName
     *
     * @return the value of cibr_sys_task.taskName
     *
     * @mbggenerated
     */
    public String getTaskname() {
        return taskname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_sys_task.taskName
     *
     * @param taskname the value for cibr_sys_task.taskName
     *
     * @mbggenerated
     */
    public void setTaskname(String taskname) {
        this.taskname = taskname == null ? null : taskname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_sys_task.taskType
     *
     * @return the value of cibr_sys_task.taskType
     *
     * @mbggenerated
     */
    public String getTasktype() {
        return tasktype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_sys_task.taskType
     *
     * @param tasktype the value for cibr_sys_task.taskType
     *
     * @mbggenerated
     */
    public void setTasktype(String tasktype) {
        this.tasktype = tasktype == null ? null : tasktype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_sys_task.taskstatu
     *
     * @return the value of cibr_sys_task.taskstatu
     *
     * @mbggenerated
     */
    public String getTaskstatu() {
        return taskstatu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_sys_task.taskstatu
     *
     * @param taskstatu the value for cibr_sys_task.taskstatu
     *
     * @mbggenerated
     */
    public void setTaskstatu(String taskstatu) {
        this.taskstatu = taskstatu == null ? null : taskstatu.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_sys_task.creater
     *
     * @return the value of cibr_sys_task.creater
     *
     * @mbggenerated
     */
    public String getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_sys_task.creater
     *
     * @param creater the value for cibr_sys_task.creater
     *
     * @mbggenerated
     */
    public void setCreater(String creater) {
        this.creater = creater == null ? null : creater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_sys_task.createTime
     *
     * @return the value of cibr_sys_task.createTime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_sys_task.createTime
     *
     * @param createtime the value for cibr_sys_task.createTime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_sys_task.remark
     *
     * @return the value of cibr_sys_task.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_sys_task.remark
     *
     * @param remark the value for cibr_sys_task.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}