package com.cibr.vectorservice.dao;

import com.cibr.vectorservice.entity.CibrTaskRaav;
import com.cibr.vectorservice.entity.CibrTaskRaavExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface CibrTaskRaavMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_raav
     *
     * @mbggenerated
     */
    int countByExample(CibrTaskRaavExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_raav
     *
     * @mbggenerated
     */
    int deleteByExample(CibrTaskRaavExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_raav
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_raav
     *
     * @mbggenerated
     */
    int insert(CibrTaskRaav record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_raav
     *
     * @mbggenerated
     */
    int insertSelective(CibrTaskRaav record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_raav
     *
     * @mbggenerated
     */
    List<CibrTaskRaav> selectByExample(CibrTaskRaavExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_raav
     *
     * @mbggenerated
     */
    CibrTaskRaav selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_raav
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CibrTaskRaav record, @Param("example") CibrTaskRaavExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_raav
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CibrTaskRaav record, @Param("example") CibrTaskRaavExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_raav
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CibrTaskRaav record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_raav
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CibrTaskRaav record);

    void batchInsert(@Param("list") List<CibrTaskRaav> list);
}