package com.cibr.vectorservice.dao;

import com.cibr.vectorservice.entity.CibrSysTask;
import com.cibr.vectorservice.entity.CibrSysTaskExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface CibrSysTaskMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_task
     *
     * @mbggenerated
     */
    int countByExample(CibrSysTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_task
     *
     * @mbggenerated
     */
    int deleteByExample(CibrSysTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_task
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_task
     *
     * @mbggenerated
     */
    int insert(CibrSysTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_task
     *
     * @mbggenerated
     */
    int insertSelective(CibrSysTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_task
     *
     * @mbggenerated
     */
    List<CibrSysTask> selectByExample(CibrSysTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_task
     *
     * @mbggenerated
     */
    CibrSysTask selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_task
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CibrSysTask record, @Param("example") CibrSysTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_task
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CibrSysTask record, @Param("example") CibrSysTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_task
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CibrSysTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_task
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CibrSysTask record);

    List<CibrSysTask> getAllTask(@Param("userIds") List<String> userId);
}